// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uumxqcntlfwqokwpleoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1bXhxY250bGZ3cW9rd3BsZW9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0ODIwNzMsImV4cCI6MjA1MjA1ODA3M30.PB8YwCO68ghrT4DjOvjEXM-dxpb99S8EftJKzEYwN4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);